export interface Guest {
  id: number;
  fullName: string;
  firstName: string;
  lastName: string;
  country: string;
  citizenshipCode: string;
  dateOfBirth: string;
  yearsOld: number;
  gender: string;
  dateOfIssue: string;
  expiryDate: string;
  passportNumber: string;
  issuedBy: string;
  visaNumber: string;
  visaFrom: string;
  visaTo: string;
  hasVisa: boolean;
  parentId: number | null;
  notes: string;
  phone: string;
  reservationId: number;
  createdAt: string;
}

export interface Reservation {
  id: number;
  name: string;
  checkIn: string;
  checkOut: string;
  platform: string;
  linkedEventUid?: string | null;
  /** Exact platform namespace for linkedEventUid. Kept separate from
   *  platform because a manually paid extension is a Direct booking linked
   *  to (for example) an Airbnb event. */
  linkedEventPlatform?: string | null;
  /** How this local row relates to its synced event. Claims overlap the
   *  source; extensions are separate Direct segments that abut it. */
  linkedEventRole?: "claim" | "extension" | null;
  /** Per-reservation messenger group URLs. Set when the host has
   *  created a one-off group chat for this booking (Telegram or
   *  WhatsApp) and saved its URL here, so the "Open group" button in
   *  the reservation view can deep-link straight into it. */
  tgGroupUrl?: string | null;
  waGroupUrl?: string | null;
  /** Host-editable override for the messenger group-chat name. When
   *  null/absent, the reservation view auto-generates one from the
   *  platform, dates, guest, and property. */
  groupName?: string | null;
  /** Reservation-level contact phone (loose E.164). Drives the
   *  personal-chat WhatsApp / Telegram quick-buttons even on bookings
   *  with no passport guests. */
  phone?: string | null;
  /** Confirmed number of travelers in this booking. */
  bookedGuestCount?: number | null;
  /** Money in minor units (cents) of the account currency. Null until
   *  the host enters a price or a payout import matches the booking. */
  grossCents?: number | null;
  hostFeeCents?: number | null;
  cleaningFeeCents?: number | null;
  payoutCents?: number | null;
  propertyId: number;
  createdAt: string;
  guests?: Guest[];
  _count?: { guests: number };
}

export interface Property {
  id: number;
  userId: number; // owner
  name: string;
  minNights: number;
  checkInTime: string;  // "HH:MM" — guest arrival time, e.g. "14:00"
  checkOutTime: string; // "HH:MM" — guest departure time, e.g. "12:00"
  bookingWindow: number; // days forward from today to consider bookings; beyond this, events are ignored
  cleaningEnabled: boolean; // master toggle for buffer / sameDayCleaning / potentialCleaning / unbookable computation
  feedToken: string | null; // optional token gating the public iCal feed
  /** Smart-lock device bound to this property (Tuya device_id). */
  lockDeviceId?: string | null;
  lockDeviceName?: string | null;
  createdAt: string;
  reservations: Reservation[];
}

export interface CalendarLink {
  id: number;
  propertyId: number;
  platform: string;
  icalExportUrl: string;
  bufferBefore: number;
  bufferAfter: number;
  lastFetchedAt: string | null;
  lastError: string | null;
  failureCount: number;
  createdAt: string;
}

export interface CalendarEvent {
  id: number;
  propertyId: number;
  platform: string;
  uid: string;
  summary: string;
  startDate: string;
  endDate: string;
  createdAt: string;
}

export const EXPENSE_CATEGORIES = [
  "cleaning",
  "wifi",
  "water",
  "electricity",
  "gas-bottle",
  "insurance",
  "supplies",
  "maintenance",
  "other",
] as const;
export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export interface Expense {
  id: number;
  propertyId: number;
  /** YYYY-MM-DD calendar day — reports bucket by local month. */
  date: string;
  category: ExpenseCategory;
  /** Minor units (cents) of the account currency. */
  amountCents: number;
  note: string;
  reservationId: number | null;
  /** Shared id for rows generated by a monthly repeat; null = one-off. */
  recurGroup: string | null;
  createdById: number;
  createdAt: string;
}

export interface DateOverride {
  id: number;
  propertyId: number;
  date: string;
  type: "open" | "closed";
  note: string;
  createdAt: string;
}

/**
 * Compute the cutoff date string (YYYY-MM-DD) for a booking window.
 * Events starting on or after this date should be ignored.
 */
export function bookingWindowCutoff(windowDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + windowDays);
  return d.toISOString().substring(0, 10);
}

export interface SyncLogEntry {
  id: number;
  propertyId: number | null;
  level: string;
  message: string;
  createdAt: string;
}
