import type { MetadataRoute } from "next";
import { prisma } from "@/lib/prisma";
import { SUPPORTED_LOCALES, DEFAULT_LOCALE, SITE_URL } from "@/lib/i18n/alternates";
import type { Locale } from "@/lib/i18n/translations";

// Force per-request rendering. ISR (revalidate=N) wasn't enough — the
// build still pre-renders sitemap() once on the GH Actions runner where
// there's no DB, ships an empty snapshot, and serves that for the first
// `revalidate` window. force-dynamic skips the build-time render
// entirely, so /sitemap.xml is always generated by the droplet against
// the live DB. Crawl traffic on a sitemap is a few hits per day —
// running one Prisma query each is fine.
export const dynamic = "force-dynamic";

// Build a per-locale URL for a given default-locale path.
//   "/" + "ru" → "/ru"
//   "/blog/foo" + "ru" → "/ru/blog/foo"
//   "/blog/foo" + "en" → "/blog/foo"  (default-no-prefix)
function localizedUrl(defaultPath: string, locale: Locale): string {
  if (locale === DEFAULT_LOCALE) return `${SITE_URL}${defaultPath}`;
  if (defaultPath === "/") return `${SITE_URL}/${locale}`;
  return `${SITE_URL}/${locale}${defaultPath}`;
}

// Build the alternates.languages map for a given default-locale path.
// Used as the per-row `alternates: { languages: ... }` so Google sees
// each entry's hreflang siblings inside the sitemap itself
// (matches `<xhtml:link rel="alternate" hreflang="…">` in raw XML).
//
// `x-default` is added so the sitemap signals match what the per-page
// `generateMetadata` already emits via `localizedAlternates` —
// without it, Google sees inconsistent hreflang declarations between
// the page head and the sitemap and falls back to its own heuristics.
// `x-default` always points at the default-locale URL (the canonical
// fallback when Google can't determine the visitor's preference).
function altLanguages(defaultPath: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const loc of SUPPORTED_LOCALES) {
    result[loc] = localizedUrl(defaultPath, loc);
  }
  result["x-default"] = localizedUrl(defaultPath, DEFAULT_LOCALE);
  return result;
}

/**
 * Sitemap. Per-locale entries for every public marketing page + every
 * published blog post + every qualifying tag page. Each entry carries
 * `alternates.languages` pointing at every language version of the
 * same logical page — Next.js renders these as
 * `<xhtml:link rel="alternate" hreflang="…">` so Google can pair the
 * versions and rank each in its own market.
 *
 * `lastModified` = `updatedAt` when set, otherwise `publishedAt` —
 * Google uses this signal to decide whether to recrawl, so we want it
 * to actually move when an editor saves a post.
 *
 * Drafts and future-scheduled posts are filtered out so the public
 * sitemap matches what /blog actually surfaces.
 */
// Deploy-time constant for static-page lastmod. Using `new Date()` per
// request told Google "everything changed every crawl," which Google
// down-weights as a noisy signal and falls back to its own heuristics.
// The deploy SHA is set during the build step (NEXT_PUBLIC_GIT_COMMIT_SHA);
// we hash it into a Date pinned to the deploy. When the deploy SHA
// doesn't change, lastmod doesn't change. When you push a new build,
// every static lastmod jumps forward together.
const DEPLOY_LASTMOD_SOURCE =
  process.env.VERCEL_GIT_COMMIT_DATE ||
  process.env.NEXT_PUBLIC_GIT_COMMIT_DATE ||
  process.env.SOURCE_DATE_EPOCH ||
  "";
const STATIC_LASTMOD = (() => {
  if (DEPLOY_LASTMOD_SOURCE) {
    const ts = Number(DEPLOY_LASTMOD_SOURCE);
    if (Number.isFinite(ts) && ts > 0) return new Date(ts * 1000);
    const parsed = new Date(DEPLOY_LASTMOD_SOURCE);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  // Fallback: ISO date pinned to today's date at build time. Better than
  // a per-request `new Date()` because the value is captured once when
  // the bundle loads and stays stable for the lifetime of the running
  // process — multiple sitemap requests in the same dyno still get the
  // same timestamp instead of drifting by milliseconds.
  return new Date();
})();

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  // Use the deploy-pinned timestamp for static surfaces; only blog rows
  // (which have a real `updatedAt`) override it with their own freshness.
  const staticLastmod = STATIC_LASTMOD;

  // Static marketing surfaces. Each `localized: true` path generates one
  // entry per supported locale with hreflang siblings; `localized: false`
  // paths emit a single EN-only entry (used for legal copy that hasn't
  // been professionally translated — see middleware's LOCALIZABLE_PATHS
  // for the matching list).
  const staticPaths: Array<{
    path: string;
    changeFrequency: "weekly" | "monthly" | "yearly" | "daily";
    priority: number;
    localized: boolean;
  }> = [
    { path: "/", changeFrequency: "weekly", priority: 1.0, localized: true },
    { path: "/onboard", changeFrequency: "monthly", priority: 0.9, localized: true },
    { path: "/blog", changeFrequency: "daily", priority: 0.9, localized: true },
    { path: "/signup", changeFrequency: "monthly", priority: 0.8, localized: true },
    { path: "/login", changeFrequency: "monthly", priority: 0.6, localized: true },
    { path: "/terms", changeFrequency: "yearly", priority: 0.3, localized: false },
    { path: "/privacy", changeFrequency: "yearly", priority: 0.3, localized: false },
  ];

  const staticEntries: MetadataRoute.Sitemap = [];
  for (const entry of staticPaths) {
    if (entry.localized) {
      const languages = altLanguages(entry.path);
      for (const loc of SUPPORTED_LOCALES) {
        staticEntries.push({
          url: localizedUrl(entry.path, loc),
          lastModified: staticLastmod,
          changeFrequency: entry.changeFrequency,
          priority: entry.priority,
          alternates: { languages },
        });
      }
    } else {
      staticEntries.push({
        url: localizedUrl(entry.path, DEFAULT_LOCALE),
        lastModified: staticLastmod,
        changeFrequency: entry.changeFrequency,
        priority: entry.priority,
      });
    }
  }

  // Below this many posts a tag page is "thin content" — Google ranks it
  // as low-value duplicate-of-the-blog-index and that drag spreads to
  // the sitemap. 3 is the line every major SEO post-mortem (Moz,
  // Ahrefs) settles on for blog taxonomies.
  const TAG_INDEX_MIN_POSTS = 3;

  let postEntries: MetadataRoute.Sitemap = [];
  let tagEntries: MetadataRoute.Sitemap = [];
  try {
    // Blog posts are stored per-locale in the DB (BlogPost.locale). The
    // grouping below builds, for every distinct slug, the set of locales
    // that have a published row. The hreflang siblings emitted for each
    // entry list ONLY those locales — pointing hreflang at a URL whose
    // row doesn't exist would feed Google a 404 and tank the canonical's
    // ranking signal alongside it. As of the catalog backfill (commit
    // f14a1b4), every active locale has a row for every slug, so each
    // post emits a full 5-language alternates map plus x-default.
    const posts = await prisma.blogPost.findMany({
      where: { status: "published", publishedAt: { lte: now } },
      select: {
        slug: true,
        locale: true,
        tagsJson: true,
        publishedAt: true,
        updatedAt: true,
      },
      orderBy: { publishedAt: "desc" },
    });

    // Group posts by slug to find translation pairs.
    const slugLocales = new Map<string, Set<string>>();
    for (const p of posts) {
      const set = slugLocales.get(p.slug) ?? new Set<string>();
      set.add(p.locale);
      slugLocales.set(p.slug, set);
    }

    postEntries = posts.map((p) => {
      const path = `/blog/${p.slug}`;
      const availableLocales = slugLocales.get(p.slug) ?? new Set<string>();
      const languages: Record<string, string> = {};
      for (const loc of SUPPORTED_LOCALES) {
        if (availableLocales.has(loc)) {
          languages[loc] = localizedUrl(path, loc);
        }
      }
      // x-default points at the EN URL when an EN row exists. EN is the
      // canonical fallback in our content model (the default locale,
      // every Stripe-style untranslated fallback consolidates onto it).
      // Skip x-default if for some edge case there's no EN row — that
      // would mean the slug exists only in non-default locales, in which
      // case there's no obvious fallback URL to declare.
      if (availableLocales.has(DEFAULT_LOCALE)) {
        languages["x-default"] = localizedUrl(path, DEFAULT_LOCALE);
      }
      return {
        url: localizedUrl(path, p.locale as Locale),
        lastModified: p.updatedAt ?? p.publishedAt ?? now,
        changeFrequency: "monthly" as const,
        priority: 0.7,
        alternates: { languages },
      };
    });

    // Count EN-locale posts per tag for the indexability threshold.
    // (Tag pages are emitted only for the default locale today —
    // each language gets its own tag page surface when it has its own
    // post library.)
    const tagPostCount = new Map<string, number>();
    const tagLastMod = new Map<string, Date>();
    for (const p of posts) {
      if (p.locale !== DEFAULT_LOCALE) continue;
      let tagSlugs: string[] = [];
      try {
        const arr = JSON.parse(p.tagsJson) as unknown;
        if (Array.isArray(arr)) tagSlugs = arr.filter((t): t is string => typeof t === "string");
      } catch {
        /* malformed row — skip its tags rather than crash */
      }
      const lastMod = p.updatedAt ?? p.publishedAt ?? now;
      for (const slug of tagSlugs) {
        tagPostCount.set(slug, (tagPostCount.get(slug) ?? 0) + 1);
        const prev = tagLastMod.get(slug);
        if (!prev || lastMod > prev) tagLastMod.set(slug, lastMod);
      }
    }

    const tags = await prisma.blogTag.findMany({
      where: { locale: DEFAULT_LOCALE },
      select: { slug: true, createdAt: true },
    });
    tagEntries = tags
      .filter((t) => (tagPostCount.get(t.slug) ?? 0) >= TAG_INDEX_MIN_POSTS)
      .map((t) => ({
        url: `${SITE_URL}/blog/tag/${encodeURIComponent(t.slug)}`,
        lastModified: tagLastMod.get(t.slug) ?? t.createdAt,
        changeFrequency: "weekly" as const,
        priority: 0.5,
      }));
  } catch (err) {
    console.warn("sitemap: failed to load blog rows", err);
  }

  return [...staticEntries, ...postEntries, ...tagEntries];
}
